### PR TITLE
updating tweepy authentication to v2

### PR DESCRIPTION
**Pull request by bhaskar2443053**
This PR fixes https://github.com/asyml/forte/issues/716

### Description of changes
Describe what are the changes, and how they solve the problem.

1) twitte api v2 update is compatible with tweepy 4.0
I have made changes to setup file accordingly

2) updated the code for extracting tweets with authentication with Bearer Token 
src/tweepy/fortex/tweepy/twittersearch_processor.py

### Possible influences of this PR.
Describe what are the possible side-effects of the code change.

### Test Conducted
Describe what test cases are included for the PR.

### CODE REVIEW

**Comment by hunterhector** [comment]
PR message should be:

`This PR fixes https://github.com/asyml/forte/issues/716`

**Review by hunterhector — COMMENTED** [review]
Let's get the CI check pass first.

Other than that, we are missing the test cases for the processor (that's why it failed silently before). Let's add simple test cases here: https://github.com/asyml/forte-wrappers/tree/main/tests/wrappers

**Comment by hunterhector** [comment]
1. please update the GitHub message
2. accept the invite to the repo so the CI without approval

**Comment by hunterhector** [comment]
Let's pass the CI before we can review this PR

**Comment by bhaskar2443053** [comment]
> 

working on it

**Comment by bhaskar2443053** [comment]
> Let's pass the CI before we can review this PR

Hi Hector,
I have this dependency issue with tweepy.
I think it is due to the setup file tweepy version modification. tweepy==3.10.0 > 4.0

how do I solve this ?


Run for dep in allennlp elastic faiss gpt[2](https://github.com/asyml/forte-wrappers/runs/5881313007?check_suite_focus=true#step:11:2) huggingface nltk spacy stanza tweepy vader
  for dep in allennlp elastic faiss gpt2 huggingface nltk spacy stanza tweepy vader
    do
      mypy "src/"$dep
    done
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/asyml/forte-wrappers/runs/5881313007?check_suite_focus=true#step:11:3).6.15/x6[4](https://github.com/asyml/forte-wrappers/runs/5881313007?check_suite_focus=true#step:11:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.6.1[5](https://github.com/asyml/forte-wrappers/runs/5881313007?check_suite_focus=true#step:11:5)/x[6](https://github.com/asyml/forte-wrappers/runs/5881313007?check_suite_focus=true#step:11:6)4/lib
Success: no issues found in 4 source files
Success: no issues found in 6 source files
Success: no issues found in 3 source files
Success: no issues found in 3 source files
Success: no issues found in [11](https://github.com/asyml/forte-wrappers/runs/5881313007?check_suite_focus=true#step:11:11) source files
Success: no issues found in 3 source files
Success: no issues found in 3 source files
Success: no issues found in 3 source files
src/tweepy/fortex/tweepy/twittersearch_processor.py:[13](https://github.com/asyml/forte-wrappers/runs/5881313007?check_suite_focus=true#step:11:13)2: error: Module has no attribute "Client"
Found 1 error in 1 file (checked 3 source files)
Error: Process completed with exit code 1.

**Comment by hunterhector** [comment]
> > tweepy 4.0 works fine in local setup.
> > I think we need to change the setup file in the master, as the build depends on the setup file in master.

what do you mean by in master? You can change relevant files in this PR.

**Comment by hunterhector** [comment]
also note that this is a mypy error. Try reproduce locally by following the workflow until here https://github.com/asyml/forte-wrappers/blob/main/.github/workflows/main.yml#L72

**Comment by bhaskar2443053** [comment]
> WIP: [tweepy/tweepy#1828](https://github.com/tweepy/tweepy/pull/1828)

Hi Hector, with #type : ignore the mypy error was bypassed.
all checks have passed now.

**Comment by bhaskar2443053** [comment]
@hunterhector could you review the PR again ?

**Review by hunterhector — APPROVED** [review]

**Pull request merged**
