### PR TITLE
Import statements fixed in example

### PR DESCRIPTION
**Pull request by Piyush13y**
This tiny PR fixes [#82](https://github.com/asyml/forte-wrappers/issues/82) 

### Description of changes
import statements fixed

### Possible influences of this PR.
The example shouldn't throw `ModuleNotFound` exception anymore.

### CODE REVIEW

**Review by hunterhector — COMMENTED** [review]
Thanks for the fix. 

As for the mypy error, this is due to we updated numpy version in texar, which now contains its own typing files. So we would need to fix a few typing issues accordingly.

It might not be possible to fix typing for all different python version and numpy version, it is sufficient to only test on the newest numpy and newest python version.

So we would need to change this:
https://github.com/asyml/forte-wrappers/blob/main/.github/workflows/main.yml#L68

to something similar as:

https://github.com/asyml/forte/blob/master/.github/workflows/main.yml#L94

**Comment by Piyush13y** [comment]
@hunterhector Is a fix for this typing issue in progress? Or do you want me to pick it? Because there are more changes coming in to Forte-wrappers related to the ontology namespace consistency.

**Comment by hunterhector** [comment]
> @hunterhector Is a fix for this typing issue in progress? Or do you want me to pick it? Because there are more changes coming in to Forte-wrappers related to the ontology namespace consistency.

We don't have anything in progress for forte-wrapper now, you probably need to study this.

**Comment by hunterhector** [comment]
> 

Updates on this. We have updated the texar-pytorch side with numpy typings. But now the new numpy versions causes a few typing errors in this repo that need to be fixed too.

**Comment by Piyush13y** [comment]
Thanks for the information. I don't feel this is a priority change. We can wait till the fix is out, I will re-request a review, once it passes all the checks.

**Pull request merged**
